### ISSUE TITLE
Error when running for first time.

### ISSUE THREAD

**Issue by elliot-james** [roeland-frans/mindmeister-csv#1]
Good afternoon, 

Not sure if you're tracking this still as it's been 7 years, but when I try running the script on my JN I receive the error:

```
File "C:\Users\ejroy\AppData\Local\Temp/ipykernel_22480/2687207147.py", line 96
    print row
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(row)?
```

Any idea why this might be?

**Comment by elliot-james** [comment]
Showing my inexperience here - this is apparently due to the transfer between Python 2.X and Python 3.X.

Have you had any joy running this script in a Python 3.X environment?

**Comment by roeland-frans** [comment]
Thanks for the report. Correct, I've not used or maintained this script in years so I've not ported the script to Python 3.

I'll port this script to Python 3 and update the docs in the coming week.

What Python version are you currently running?

**Comment by elliot-james** [comment]
Hi Roeland, thanks for your response.

I'm currently running Python 3.8 on my machine.
